version: '3'
services:
  nodejs:
    build:
      context: ./
      dockerfile: Dev.Dockerfile
    volumes:
      - './:/www'
      - '/www/node_modules'
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: docker-monitor
    env_file:
      - .env
    ports:
      - '1300:1300'
    stdin_open: true
networks:
  default:
    external:
      name: develop
