version: '3'
services:
  nodejs:
    build:
      context: ./
      dockerfile: Dev.Dockerfile
    volumes:
      - './:/app'
      - '/app'
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: docker-monitor
    env_file:
      - .env
    ports:
      - '3000:3000'
    stdin_open: true
networks:
  default:
    name: develop
